version: "3.8"

services:
  db:
    image: "mysql:8.2"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mtl"
      MYSQL_USER: "mtl"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"

